services:
  app:
    build:
      context: .
    image: node-app:latest
    env_file: .env
    networks:
      - web_net
      - postgres_subnet
      - mongo_subnet
    depends_on:
      - postgres
      - mongo
    ports:
      #- '3000:3000' # Expose app port for direct access if needed
      - '9229:9229' # Expose Node.js debugger port
    volumes:
      - ./:/srv/app
    environment:
      - NODE_ENV=development
      - PG_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - MONGO_DATABASE_URL=mongodb://mongo:27017

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/secrets/.htpasswd:/etc/nginx/.htpasswd:ro # https://hostingcanada.org/htpasswd-generator/
      - ./nginx/secrets/certs:/etc/nginx/certs:ro # SSL certificates
      - ./static:/usr/share/nginx/static:ro
      - ./html:/usr/share/nginx/html:ro
    networks:
      - web_net

  postgres:
    image: postgres:latest
    networks:
      - postgres_subnet
    ports:
      #   - "5432:5432"    # PostgreSQL port
      - ${DEV_POSTGRES_PORT:-}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  mongo:
    image: mongo:latest
    networks:
      - mongo_subnet
    ports:
      #   - "27017:27017"  # MongoDB port
      - ${DEV_MONGO_PORT:-}
    volumes:
      - mongo-data:/data/db

networks:
  web_net:
    driver: bridge
  mongo_subnet:
    driver: bridge

  postgres_subnet:
    driver: bridge

volumes:
  postgres-data:
  mongo-data:
